import Header from '@/components/Header'
import './globals.scss'
import localFont from 'next/font/local'

const Mont = localFont({
  src: [
    {
      path: '../fonts/bold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/normal.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/normal.woff',
      weight: '300',
      style: 'normal',
    },
  ],
})

export const metadata = {
  title: 'Create Next App 1',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="cs">
      <body className={Mont.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
